version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - supabase-local
    networks:
      - astramentor-network

  # Supabase local para desenvolvimento (opcional)
  supabase-local:
    image: supabase/supabase-local
    ports:
      - "54321:54321" # REST
      - "54322:54322" # Studio
    environment:
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - astramentor-network

networks:
  astramentor-network:
    driver: bridge

volumes:
  supabase-data:

