FROM node:18-alpine

WORKDIR /app

# Instalação de dependências necessárias
RUN apk add --no-cache libc6-compat

# Copia os arquivos de configuração
COPY package.json package-lock.json* ./
COPY .npmrc ./

# Instala as dependências
RUN npm install

# Expõe a porta que a aplicação usará
EXPOSE 3000

# Comando para iniciar a aplicação em modo de desenvolvimento
CMD ["npm", "run", "dev"]

